### ISSUE TITLE
Bad request, response code 500

### ISSUE THREAD

**Issue by zezhuo** [cran/gprofiler2#1]
Hi @gaborcsardi , 

I found gorth function will return a error when inquiring "Gm1123" gene. Same problem for the web-based gprofiler.
gprofiler2 is a good tool. Wish you fix this problem. 

```
> gorth("Gm1123", 
+                  source_organism = "mmusculus", 
+                  target_organism = "hsapiens", 
+                  filter_na = F) 
Error in gorth("Gm1123", source_organism = "mmusculus", target_organism = "hsapiens",  : 
  Bad request, response code 500
```

Regards,
Nelson

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package maintainers in the `DESCRIPTION` file. Thanks!
